name: Rust

on:
  push:
    branches: [ main, develop, actions ]
  pull_request:
    branches: [ main, develop, actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Snekdown
      run: cargo install snekdown --all-features
    - name: Create dist
      run: mkdir dist
    - name: Build
      run: snekdown render main.md dist/index.html
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation.html
        path: dist/index.html
